/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldWorldIdIndexRouteImport } from './routes/world/$worldId/index'
import { Route as WorldWorldIdRoomIdRouteImport } from './routes/world/$worldId/$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldWorldIdIndexRoute = WorldWorldIdIndexRouteImport.update({
  id: '/world/$worldId/',
  path: '/world/$worldId/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldWorldIdRoomIdRoute = WorldWorldIdRoomIdRouteImport.update({
  id: '/world/$worldId/$roomId',
  path: '/world/$worldId/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/world/$worldId/$roomId': typeof WorldWorldIdRoomIdRoute
  '/world/$worldId/': typeof WorldWorldIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/world/$worldId/$roomId': typeof WorldWorldIdRoomIdRoute
  '/world/$worldId': typeof WorldWorldIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/world/$worldId/$roomId': typeof WorldWorldIdRoomIdRoute
  '/world/$worldId/': typeof WorldWorldIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/world/$worldId/$roomId' | '/world/$worldId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/world/$worldId/$roomId' | '/world/$worldId'
  id: '__root__' | '/' | '/world/$worldId/$roomId' | '/world/$worldId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorldWorldIdRoomIdRoute: typeof WorldWorldIdRoomIdRoute
  WorldWorldIdIndexRoute: typeof WorldWorldIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/$worldId/': {
      id: '/world/$worldId/'
      path: '/world/$worldId'
      fullPath: '/world/$worldId/'
      preLoaderRoute: typeof WorldWorldIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/$worldId/$roomId': {
      id: '/world/$worldId/$roomId'
      path: '/world/$worldId/$roomId'
      fullPath: '/world/$worldId/$roomId'
      preLoaderRoute: typeof WorldWorldIdRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorldWorldIdRoomIdRoute: WorldWorldIdRoomIdRoute,
  WorldWorldIdIndexRoute: WorldWorldIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
